---
title: "NC Absentee Ballots"
author: "Ben Wallace"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, include=FALSE}
library(tidyverse)
library(dplyr)
library(reshape2)
library(cowplot)
```

NC data taken OCT 18, 2020

```{r data, include = FALSE}
requests <- read_csv("data/absentee_requests.csv")
returns <- read_csv("data/absentee_returns.csv")
```

```{r clean requests}
requests <- requests %>%
  rename(count = group_count,
         county = county_name,
         ethnicity = ethncity_desc,
         race = race_desc) %>%
  filter(county == c("DURHAM","GUILFORD","SCOTLAND","ORANGE","WATAUGA"))

requests$ethnicity = recode(requests$ethnicity, `NOT HISPANIC or NOT LATINO` = "nonhispanic" , `HISPANIC or LATINO` = "hispanic", `UNDESIGNATED` = "undesignated")

requests$race = recode(requests$race, `BLACK or AFRICAN AMERICAN` = "Black", `INDIAN AMERICAN or ALASKA NATIVE` = "indianamerican", `TWO or MORE RACES` = "multiracial", `WHITE` = "White", `UNDESIGNATED` = "undesignated", `ASIAN` = "Asian", `NATIVE HAWAIIAN or PACIFIC ISLANDER` = "pacislander", `OTHER` = "Other")

requests$race <- fct_other(requests$race, keep = c("White", "Black"), other_level = "Other") 
```

```{r clean returns}
returns <- returns %>%
  select(county_desc, race, ethnicity, ballot_rtn_status) %>%
  rename(county = county_desc,
         rtn_status = ballot_rtn_status) %>%
  filter(county == c("DURHAM","GUILFORD","SCOTLAND", "ORANGE", "WATAUGA"))

returns$ethnicity = recode(returns$ethnicity, `NOT HISPANIC or NOT LATINO` = "nonhispanic", `HISPANIC or LATINO` = "hispanic", `UNDESIGNATED` = "undesignated", `ASIAN` = "Asian", `NATIVE HAWAIIAN or PACIFIC ISLANDER` = "pacislander", `OTHER` = "Other")

returns$race = recode(returns$race, `BLACK or AFRICAN AMERICAN` = "Black", `INDIAN AMERICAN or ALASKA NATIVE` = "indianamerican", `TWO or MORE RACES` = "multiracial", `WHITE` = "White", `UNDESIGNATED` = "undesignated", `ASIAN` = "Asian", `NATIVE HAWAIIAN or PACIFIC ISLANDER` = "pacislander", `OTHER` = "Other")
  
returns$race <- fct_other(returns$race, keep = c("White", "Black"), other_level = "Other")
```

```{r totaling counts}

reqtotals <- requests %>%
  filter(ethnicity != "hispanic") %>%
  select(county, race, count) %>%
  group_by(county, race) %>%
  summarise(requests = sum(count))
  

rettotals <- returns %>%
  filter(ethnicity != "hispanic") %>%
  mutate(accepted = rtn_status == "ACCEPTED") %>%
  group_by(county, race, accepted) %>%
  summarise(returncount = n())

rettotals2 <- rettotals %>%
  pivot_wider(names_from = accepted, values_from = returncount)

totals <- dplyr::bind_cols(reqtotals, rettotals2) %>%
  select(county, race, requests, `TRUE`, `FALSE`)
```

```{r hispanic}
hispanicreq <- requests %>%
  filter(ethnicity == "hispanic") %>%
  select(county, count) %>%
  mutate(race = "Latino/Hispanic") %>%
  group_by(county) %>%
  summarise(requests = sum(count))

hispanicret <- returns %>%
  filter(ethnicity == "hispanic") %>%
  mutate(accepted = rtn_status == "ACCEPTED") %>%
  group_by(county, accepted) %>%
  summarise(returncount = n()) %>%
  mutate(race = "Latino/Hispanic") %>%
  pivot_wider(names_from = accepted, values_from = returncount)

hispanic <- dplyr::bind_cols(hispanicreq, hispanicret) 

totals <- bind_rows(totals, hispanic) %>%
  select(race, county, `TRUE`, `FALSE`, requests)
```

```{r Demographic data}
totals <- totals %>%
  arrange(county, race) %>%
  distinct() %>%
  mutate(pctpop = "") %>%
  rename(accepted = `TRUE`, rejected = `FALSE`)

x <- c(36.4, 13.7, (100-36.4-13.7-43), 43, 35.4, 8.4, (100-35.4-8.4-49.4), 49.4, 11.8, 8.6,(100-11.8-8.6-69.5), 69.5, 38.9, 3.3, (100-38.9-3.3-42.5), 42.5, 1.8, 4, (100-1.8-4-91.4), 91.4)

totals$pctpop <- x
```


```{r percentage req/accpt}
  
totals <- totals %>%
  mutate(pctaccpt = accepted / requests * 100) 
  
totals <- totals %>%
  group_by(county) %>%
  mutate(pctrqst = requests/sum(requests) * 100)
```

*Visualizations*

```{r requested vs. population}

totals_long <- totals %>%
  select(pctrqst, everything()) %>%
  pivot_longer(cols = c("pctrqst", "pctpop"), names_to = c("stats"))

p1a <- totals_long %>%
  filter(county == "DURHAM") %>%
  ggplot(aes(x = race, y = value, fill = stats)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  scale_fill_manual(values = c("steelblue1", "navy"), name = "", labels = c("Share of Population", "Share of Requested Ballots")) +
  labs(x = "Race", y = "Percent") +
  scale_y_continuous(breaks=seq(0,100,10)) +
  theme_cowplot()


p1b <- totals_long %>%
  filter(county == "GUILFORD") %>%
  ggplot(aes(x = race, y = value, fill = stats)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  scale_fill_manual(values = c("steelblue1", "navy"), name = "", labels = c("Share of Population", "Share of Requested Ballots")) +
  labs(x = "Race", y = "Percent") +
  scale_y_continuous(breaks=seq(0,100,10)) +
  theme_cowplot()

p1c <- totals_long %>%
  filter(county == "ORANGE") %>%
  ggplot(aes(x = race, y = value, fill = stats)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  scale_fill_manual(values = c("steelblue1", "navy"), name = "", labels = c("Share of Population", "Share of Requested Ballots")) +
  labs(x = "Race", y = "Percent") +
  scale_y_continuous(breaks=seq(0,100,10)) +
  theme_cowplot()


p1d <- totals_long %>%
  filter(county == "SCOTLAND") %>%
  ggplot(aes(x = race, y = value, fill = stats)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  scale_fill_manual(values = c("steelblue1", "navy"), name = "", labels = c("Share of Population", "Share of Requested Ballots")) +
  labs(x = "Race", y = "Percent") +
  scale_y_continuous(breaks=seq(0,100,10)) +
  theme_cowplot()

p1e <- totals_long %>%
  filter(county == "WATAUGA") %>%
  ggplot(aes(x = race, y = value, fill = stats)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  scale_fill_manual(values = c("steelblue1", "navy"), name = "", labels = c("Share of Population", "Share of Requested Ballots")) +
  labs(x = "Race", y = "Percent") +
  scale_y_continuous(breaks=seq(0,100,10)) +
  theme_cowplot()

p1e
```




